<?php require './templates/header.phtml' ?>

    <main class="deleteCategory">
        <div class="contenedorForm">
            <form action="deleteCategory" method="POST">
                <label for="">Eliminar categoria</label>
                <input required type="text"  value="$category"/>
                <button type="submit">Eliminar</button>
                
            </form>
        </div>
    </main>
</body>