<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <base href="<?= BASE_URL ?>"/>
    <link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>
    <header>
        <ul class="nav">
            <li><a href="home">Inicio</a></li>
            <?php if($this->isAdmin) : ?>
                <li><a href="agregar">Agregar item</a></li>
                <li><a href="select_id_editar">Editar item</a></li>
                <li><a href="select_id_eliminar">Eliminar item</a></li>
                <li><?= $_SESSION['username'];  ?></li>
            <?php else : ?>
                <li><a href="login">Login</a></li>
            <?php endif;  ?>
        </ul>
    </header>