<?php require 'templates/header.phtml'; ?>


    <main class="mainHome">
        <ul class="listaItems">
            <?php foreach ($items as $item) : 
                $name = $item->nombre;
                $image_url = $item->imagen;
                $id = $item->id; 
                $url = "modelo/" . $id;
                $category = $item->gama; ?>
                    <li>
                        <h2><a href="<?= $url ?>"><?= $name ?></a></h2>
                        <img class="fotoPc" src="<?= $image_url ?>"/>
                        <p class="categoriaItem">Gama <?= $category ?></p>
                    </li> 
            <?php endforeach ?>
        </ul>
    </main>
</body>