<?php require 'templates/header.phtml'; ?>

    <main class="centeredMain">
        <div class="contenedorForm">
            <form id="itemForm" method="POST" action="editar">
                <input type="hidden" name="id" value="<?= $id ?>"/>
                <label for="name">Nombre</label>
                <input  type="text" name="name" placeholder="Nombre" value="<?= $name ?>"/>
                <label for="cpu">Procesador</label>
                <input  type="text" name="cpu" placeholder="Procesador" value="<?= $cpu ?>"/>
                <label for="gpu">Tarjeta grafica</label>
                <input  type="text" name="gpu" placeholder="Tarjeta grafica" value="<?= $gpu ?>"/>
                <label for="motherboard">Placa base</label>
                <input  type="text" name="motherboard" placeholder="Placa base" value="<?= $motherboard ?>"/>
                <label for="storage">Almacenamiento</label>
                <input  type="text" name="storage" placeholder="Almacenamiento" value="<?= $storage ?>"/>
                <label for="ram">Ram</label>
                <input  type="number" name="ram" placeholder="Ram" value="<?= $ram ?>"/>
                
                <label for="category">Categoria</label>
                <select required name="category">
                    <option value="1">Gama alta</option>
                    <option value="2">Gama media</option>
                    <option value="3">Gama de entrada</option>
                </select>

                <label for="img">Imagen url</label>
                <input type="text" name="img" placeholder="Imagen url" value="<?= $image?>"/>
                <button type="submit">Cargar datos</button>
                <?php if ($error) : ?>
                    <div class="errorAlert">
                        <?= $error ?>
                    </div>
                <?php endif ?>
            </form>
        </div>
    </main>
</body>